[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"

[font]
size = 14
builtin_box_drawing = true 

[font.normal]
family = "MesloLGS NF"

[terminal]

[cursor]
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Underline"
blinking = "Off"
